"""Delaunay Triangulation 인덱스 매핑 분석"""
print("=" * 80)
print("Delaunay Triangulation 인덱스 매핑 분석")
print("=" * 80)

print("\n[현재 처리 방식]")
print("1. 원본 랜드마크: 478개 (468개 기본 + 10개 iris)")
print("2. 눈동자 contour 인덱스 제거: 8개 (474,475,476,477, 469,470,471,472)")
print("3. 중앙 포인트 계산 및 추가: 2개")
print("4. 최종 Delaunay 포인트: 478 - 8 + 2 = 472개 + 경계 4개 = 476개")

print("\n[문제점]")
print("- 원본 인덱스 0-467: 그대로 유지 (인덱스 0-467)")
print("- 원본 인덱스 468(왼쪽 중심): 제거됨? 아니면 유지?")
print("- 원본 인덱스 469-472(오른쪽 contour): 제거됨")
print("- 원본 인덱스 473(오른쪽 중심): 제거됨? 아니면 유지?")
print("- 원본 인덱스 474-477(왼쪽 contour): 제거됨")
print("- 추가된 중앙 포인트: 인덱스 470, 471 (Delaunay 배열 내)")

print("\n[인덱스 매핑 문제]")
print("원본 인덱스 -> Delaunay 배열 인덱스 매핑:")
print("- 0-467: 0-467 (그대로)")
print("- 468: ??? (제거됨? 아니면 유지?)")
print("- 469-472: 제거됨")
print("- 473: ??? (제거됨? 아니면 유지?)")
print("- 474-477: 제거됨")
print("- 중앙 포인트 1: 470 (Delaunay 배열 내)")
print("- 중앙 포인트 2: 471 (Delaunay 배열 내)")

print("\n[삼각형 변환 시]")
print("simplex[0], simplex[1], simplex[2]는 Delaunay 배열 인덱스")
print("이 인덱스로 original_points_array와 transformed_points_array에 접근")
print("하지만 원본 인덱스와 Delaunay 배열 인덱스가 다르면 매핑이 필요!")

print("\n[현재 코드의 문제]")
print("코드 316-318줄 주석:")
print("  'Delaunay Triangulation은 새로운 인덱스를 사용하므로'")
print("  '삼각형 변환 시에는 새로운 인덱스를 그대로 사용하면 됩니다.'")
print("  '눈동자 포인트(468-477)는 제거되고 중앙 포인트 2개로 대체되었습니다.'")
print("\n하지만 실제로는:")
print("- 인덱스 468, 473이 제거되었는지 확인 필요")
print("- 제거되었다면 인덱스 매핑 테이블이 필요")
print("- 제거되지 않았다면 중심점을 계산할 필요 없음!")

print("\n[확인 필요 사항]")
print("1. 인덱스 468, 473이 실제로 제거되는가?")
print("2. 제거된다면 인덱스 매핑 테이블이 있는가?")
print("3. 제거되지 않는다면 중심점을 계산할 필요가 있는가?")
