"""눈동자 이동 방법별 부하 분석"""
print("=" * 80)
print("눈동자 이동 방법별 부하 분석")
print("=" * 80)

print("\n[방법 1: 매핑 테이블 생성]")
print("작업:")
print("  1. 매핑 테이블 생성: O(n) - 한 번만 (n=478)")
print("  2. 드래그 시: 원본 인덱스로 업데이트 O(1)")
print("  3. Delaunay 전달 시: 매핑 테이블로 변환 O(1) per point")
print("  4. 계산: 필요 없음")
print("부하: 낮음 (한 번 생성 후 O(1) 접근)")
print("메모리: 딕셔너리 470개 항목 (약 3.7KB)")

print("\n[방법 2: 중심점 인덱스(468, 473)도 제거하고 계산된 중앙 포인트만 사용]")
print("작업:")
print("  1. contour 8개 제거: O(n)")
print("  2. 중앙 포인트 계산: O(1) - 평균 계산 (4개 포인트)")
print("  3. 중앙 포인트 추가: O(1)")
print("  4. 매핑 테이블 생성: O(n)")
print("  5. 드래그 시: 좌표만 업데이트 O(1)")
print("  6. Delaunay 전달 시: 계산된 좌표 사용 O(1)")
print("부하: 중간 (계산 + 매핑)")
print("메모리: 딕셔너리 470개 항목 + 좌표 2개")

print("\n[방법 3: 중심점 인덱스(468, 473)만 유지하고 contour만 제거]")
print("작업:")
print("  1. contour 8개만 제거: O(n)")
print("  2. 계산: 필요 없음!")
print("  3. 매핑 테이블 생성: O(n) - 하지만 작음 (2개만 필요)")
print("  4. 드래그 시: custom_landmarks[468], custom_landmarks[473] 직접 업데이트 O(1)")
print("  5. Delaunay 전달 시: 해당 인덱스의 좌표 사용 O(1)")
print("부하: 가장 낮음 (계산 없음, 매핑 최소)")
print("메모리: 딕셔너리 2개 항목만 (원본 468->Delaunay 468, 원본 473->Delaunay 469)")

print("\n" + "=" * 80)
print("성능 비교")
print("=" * 80)
print("초기화:")
print("  방법 1: O(n) - 매핑 테이블 생성")
print("  방법 2: O(n) - 제거 + 계산 + 매핑 테이블")
print("  방법 3: O(n) - 제거만 (가장 빠름)")

print("\n드래그 시:")
print("  방법 1: O(1) - 원본 인덱스로 업데이트")
print("  방법 2: O(1) - 좌표만 업데이트")
print("  방법 3: O(1) - 직접 인덱스로 업데이트 (가장 빠름)")

print("\nDelaunay 전달 시:")
print("  방법 1: O(1) - 매핑 테이블로 변환")
print("  방법 2: O(1) - 계산된 좌표 사용")
print("  방법 3: O(1) - 직접 인덱스로 접근 (가장 빠름)")

print("\n메모리:")
print("  방법 1: 매핑 테이블 470개 항목")
print("  방법 2: 매핑 테이블 470개 항목 + 좌표 2개")
print("  방법 3: 매핑 테이블 2개 항목만 (가장 적음)")

print("\n" + "=" * 80)
print("추천: 방법 3 (가장 부하가 적음)")
print("=" * 80)
print("이유:")
print("  1. 계산 불필요 (중심점 인덱스가 이미 있음)")
print("  2. 매핑 테이블 최소 (2개만)")
print("  3. 직접 인덱스 접근 가능")
print("  4. 메모리 사용 최소")
print("  5. 코드 단순")

print("\n구현:")
print("  1. contour 8개만 제거 (iris_contour_indices 사용)")
print("  2. 중심점 인덱스 468, 473은 유지")
print("  3. 드래그 시: custom_landmarks[468], custom_landmarks[473] 직접 업데이트")
print("  4. Delaunay 전달 시: custom_landmarks[468], custom_landmarks[473] 사용")
print("  5. 매핑 테이블: {468: 468, 473: 469} (간단)")
