"""눈동자 중심점 처리 방법 추천"""
print("=" * 80)
print("눈동자 중심점 처리 방법 추천")
print("=" * 80)

print("\n[현재 상황 분석]")
print("1. 폴리곤 데이터 관리:")
print("   - Delaunay Triangulation: 원본 포인트 배열 해시로 캐싱")
print("   - 인덱스 매핑: 눈동자 포인트 제거 후 중앙 포인트 추가로 인덱스 변경")
print("   - 캐시 키: hash(tuple(map(tuple, original_points_array)))")
print("2. 원래 목표:")
print("   - 눈동자 포인트 10개 → 중앙 포인트 2개로 대체")
print("   - 중심점 이동만으로 눈동자 전체 이동")

print("\n[방법 비교]")
print("\n방법 A: 10개 모두 제거 + 계산된 중앙 포인트 2개")
print("  장점:")
print("    - 원래 목표와 일치 (10개 → 2개)")
print("    - 눈동자 전체가 중앙 포인트 기준으로 정확하게 이동")
print("    - Delaunay 배열이 깔끔함 (인덱스 연속)")
print("    - 캐시 키가 안정적 (원본 포인트 배열이 일관됨)")
print("  단점:")
print("    - 중앙 포인트 계산 필요")
print("    - 드래그 시 좌표 기반 관리 필요")
print("  구현:")
print("    - contour 8개 + 중심점 2개(468, 473) 모두 제거")
print("    - 계산된 중앙 포인트 2개만 추가")
print("    - 드래그 시 좌표만 업데이트 (인덱스는 배열 끝 고정)")

print("\n방법 B: 중심점 인덱스(468, 473) 유지 + 계산된 중앙 포인트 추가")
print("  장점:")
print("    - 중심점 인덱스도 활용 가능")
print("  단점:")
print("    - 4개 포인트가 있어서 복잡")
print("    - 계산 필요")
print("    - 인덱스 매핑 복잡")

print("\n방법 C: 중심점 인덱스(468, 473)만 사용 (계획서 방법)")
print("  장점:")
print("    - 계산 불필요")
print("    - 가장 단순")
print("    - 인덱스 고정 (468, 473)")
print("  단점:")
print("    - 중심점만 이동하면 눈동자 전체가 정확하게 이동하지 않을 수 있음")
print("    - contour 포인트가 없어서 눈동자 내부 세부 변형 불가능")
print("    - 원래 목표와 다름 (10개 → 2개가 아니라 8개 제거 + 2개 유지)")

print("\n" + "=" * 80)
print("추천: 방법 A (10개 모두 제거 + 계산된 중앙 포인트 2개)")
print("=" * 80)

print("\n[추천 이유]")
print("1. 원래 목표와 일치")
print("   - 눈동자 포인트 10개 → 중앙 포인트 2개로 대체")
print("   - 목표 달성")

print("\n2. 정확도")
print("   - 눈동자 전체가 중앙 포인트 기준으로 정확하게 이동")
print("   - Delaunay Triangulation에서 중앙 포인트를 포함하는 삼각형들이 정확하게 변형")

print("\n3. 폴리곤 데이터 관리와의 호환성")
print("   - Delaunay 배열이 깔끔함 (인덱스 연속)")
print("   - 캐시 키가 안정적 (원본 포인트 배열이 일관됨)")
print("   - 인덱스 매핑이 단순함 (중앙 포인트는 항상 배열 끝)")

print("\n4. 구현 단순성")
print("   - 드래그 시 좌표만 업데이트")
print("   - 인덱스는 항상 len(landmarks) - 2, len(landmarks) - 1")
print("   - 매핑 테이블 불필요")

print("\n5. 성능")
print("   - 계산은 필요하지만 한 번만 수행 (드래그 시에는 좌표만 업데이트)")
print("   - Delaunay 캐시 재사용 가능 (원본 포인트 배열이 동일하면)")

print("\n[구현 방법]")
print("1. 눈동자 포인트 제거:")
print("   - contour 8개 (469-472, 474-477) 제거")
print("   - 중심점 2개 (468, 473) 제거")
print("   - 총 10개 제거")

print("\n2. 중앙 포인트 계산 및 추가:")
print("   - contour 8개 포인트의 평균으로 중앙 포인트 계산")
print("   - 왼쪽 중앙 포인트 추가")
print("   - 오른쪽 중앙 포인트 추가")
print("   - 인덱스: len(landmarks) - 2, len(landmarks) - 1")

print("\n3. 드래그 처리:")
print("   - 드래그 시 좌표만 업데이트")
print("   - custom_landmarks[len(landmarks) - 2] = (new_x, new_y)  # 왼쪽")
print("   - custom_landmarks[len(landmarks) - 1] = (new_x, new_y)  # 오른쪽")

print("\n4. Delaunay 전달:")
print("   - morph_face_by_polygons()에 좌표 전달")
print("   - left_iris_center_coord, right_iris_center_coord 파라미터 사용")

print("\n5. 인덱스 표시:")
print("   - 실제 Delaunay 배열 인덱스 표시")
print("   - 왼쪽: len(landmarks) - 2")
print("   - 오른쪽: len(landmarks) - 1")

print("\n[주의사항]")
print("1. 초기 계산:")
print("   - original_landmarks에서 contour 포인트로 중앙 포인트 계산")
print("   - custom_landmarks에 추가")

print("\n2. 드래그 후:")
print("   - 드래그 좌표를 custom_landmarks에 직접 업데이트")
print("   - morph_face_by_polygons()에 전달")

print("\n3. 사이즈 조정:")
print("   - 사이즈 조정 시 중앙 포인트도 함께 변환")
print("   - 변환된 좌표를 custom_landmarks에 업데이트")

print("\n" + "=" * 80)
print("결론")
print("=" * 80)
print("방법 A를 추천합니다:")
print("  - 원래 목표와 일치")
print("  - 정확도 높음")
print("  - 폴리곤 데이터 관리와 호환")
print("  - 구현 단순")
print("  - 성능 우수")
